// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShoesSopAPI.Models
{
    public partial class GioHang
    {
        public int Id { get; set; }
        public int SanPhamId { get; set; }
        public int KhachHangId { get; set; }

        public virtual KhachHang KhachHang { get; set; }
        public virtual SanPham SanPham { get; set; }
    }
}