// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShoesSopAPI.Models
{
    public partial class KhachHang
    {
        public KhachHang()
        {
            GioHangs = new HashSet<GioHang>();
            HoaDons = new HashSet<HoaDon>();
        }

        public int Id { get; set; }
        public string HoTen { get; set; }
        public string Sđt { get; set; }
        public string Email { get; set; }
        public string MatKhau { get; set; }
        public string GioiTinh { get; set; }
        public DateTime? Ngaysinh { get; set; }

        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }
}