// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace ShoesSopAPI.Models
{
    public partial class LoaiSanPham
    {
        public int Id { get; set; }
        public string TenLoai { get; set; }
    }
}