// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;
using ShoesSopAPI.Data;

namespace ShoesSopAPI.Models
{
    public partial class SanPham
    {
        public SanPham()
        {
            GioHangs = new HashSet<GioHang>();
            HoaDons = new HashSet<HoaDon>();
        }

        public int Id { get; set; }
        public string TenSanPham { get; set; }
        public int Gia { get; set; }
        public int? Sale { get; set; }
        public int Loai { get; set; }
        public string MoTa { get; set; }
        public string Anh { get; set; }
        public DateTime? NgayTao { get; set; }
        public int? CreatedbyId { get; set; }

        public virtual ICollection<GioHang> GioHangs { get; set; }
        public virtual ICollection<HoaDon> HoaDons { get; set; }
    }


}